
language: java

build:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

services:
  - mysql

before_install:
  - mysql -u root -e "GRANT ALL PRIVILEGES ON simulacionmundial.* TO 'travis'@'%';";
  - mysql -e 'CREATE SCHEMA simulacionmundial DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;'
  - sudo service mysql restart
