language: java

configurations {
    cucumberRuntime {
        extendsFrom testRuntime
    }
}

task maven.cucumber() {
    dependsOn assemble, compileTestJava
    doLast {
        javaexec {
            main = "maven.cucumber.api.cli.Main"
            classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
            args = ['--plugin', 'pretty', '--glue', 'gradle.maven.cucumber', 'src/test/resources']
        }
    }
}
