
language: java

dist: precise



services:
  - mysql

before_install:
  - mysql -u root -e "GRANT ALL PRIVILEGES ON simulacionmundial.* TO 'travis'@'%';";
  - mysql -e 'CREATE SCHEMA simulacionmundial DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart
