language: java

services:
  - mysql

build:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:

  - mvn clean verify

before_install:
  - mysql -e 'CREATE DATABASE simulacionmundial;'
  - mysql -e 'USE simulacionmundial;'


test:
  - mvn test -B